---
- name: Install asdf
  kewlfft.aur.aur:
    use: yay
    name:
      - asdf-vm
- name: Display asdf plugins
  debug: "var=asdf_plugins"
- name: Install asdf plugins
  ansible.builtin.shell: |
    source /opt/asdf-vm/asdf.sh
    {% for plugin in asdf_plugins %}
    if ! asdf plugin list | grep {{ plugin }};then
      asdf plugin add {{ plugin }}
    fi
    {% endfor %}

- name: Display extra asdf plugins
  debug: "var=asdf_plugins_extra"
  when: asdf_plugins_extra is defined
- name: Install extra asdf plugins
  ansible.builtin.shell: |
    source /opt/asdf-vm/asdf.sh
    {% for plugin in asdf_plugins_extra %}
    if ! asdf plugin list | grep {{ plugin }};then
      asdf plugin add {{ plugin }}
    fi
    {% endfor %}
