---
- name: Install Neovim
  ansible.builtin.package:
    name:
      - neovim
      - python-pynvim
    state: latest
  become: yes
- name: Create Plug install dir
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload"
    state: directory
- name: Install Plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/plug.vim"
# - name: Install plugins
#   ansible.builtin.shell: nvim +slient +VimEnter +PlugInstall +qall || true
