require("nvim-treesitter.configs").setup({
  sync_install = false,
  auto_install = false,
  highlight = {
    enable = true,
    disable = {},
  },
  indent = {
    enable = false,
    disable = {},
  },
  ensure_installed = {
    "bash",
    "c",
    "cmake",
    "css",
    "csv",
    "cue",
    "diff",
    "comment",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "gotmpl",
    "gowork",
    "gpg",
    "hcl",
    "html",
    "http",
    "ini",
    "jq",
    "json",
    "lua",
    "luadoc",
    "luap",
    "make",
    "nix",
    "passwd",
    "printf",
    "proto",
    "python",
    "rasi",
    "regex",
    "readline",
    "requirements",
    "ruby",
    "rust",
    "scss",
    "sql",
    "ssh_config",
    "terraform",
    "tmux",
    "toml",
    "udev",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
  },
})

-- local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
-- parser_config.tsx.used_by = { "javascript", "typescript.tsx" }
