---
- name: Distribution
  debug: msg="{{ ansible_distribution }}"
- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"
- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"
- name: Install required tools
  ansible.builtin.package:
    name:
      - git
      - curl
      - base-devel
    state: latest
  become: true
- name: Configure git
  ansible.builtin.template:
    dest: "{{ansible_user_dir}}/.gitconfig"
    src: gitconfig.j2
- name: Create git signers file
  copy:
    content: ""
    dest: "{{ansible_user_dir}}/.git-allowed-signers"
    force: no
    group: "{{ansible_user_gid}}"
    owner: "{{ansible_user_uid}}"
    mode: 0660
- name: Create gitconfig local file
  copy:
    content: ""
    dest: "{{ansible_user_dir}}/.gitconfig.local"
    force: no
    group: "{{ansible_user_gid}}"
    owner: "{{ansible_user_uid}}"
    mode: 0660
- name: Install yay
  kewlfft.aur.aur:
    use: makepkg
    name:
      - yay
