#!/bin/sh

sysresources=/etc/X11/xinit/.Xresources
userresources=$HOME/.Xresources
localresource=$HOME/.Xresources.local
usermodmap=$HOME/.Xmodmap
bindkeys=$HOME/.xbindkeys
sysmodmap=/etc/X11/xinit/.Xmodmap
xbindkeys=$HOME/.xbindkeysrc
hostname=$(hostname)

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$localresource" ]; then
    xrdb -merge "$localresource"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -f "$xbindkeys" ]; then
  xbindkeys
fi

# start some nice programs

# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

if [ -f "$HOME/.xinitrc.local" ];then
  . "$HOME/.xinitrc.local"
fi

#export XDG_CURRENT_DESKTOP=gnome
export XDG_CURRENT_DESKTOP=i3
export XDG_SESSION_DESKTOP="${XDG_SESSION_DESKTOP:-i3}"
export XDG_SESSION_TYPE=x11

#export TERM=xterm-256color
systemctl --user import-environment DISPLAY XDG_CURRENT_DESKTOP

#compton --config /home/simon/.compton.conf &
#xsetroot -solid "#0d1217"

. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
#autocutsel -fork &
#autocutsel -selection PRIMARY -fork &
#exec ssh-agent i3
#eval $(dbus-launch --sh-syntax)
~/.fehbg &
# type xfsettingsd > /dev/null 2>&1 && { xfsettingsd & }
# type /usr/lib/xfce-polkit/xfce-polkit > /dev/null 2>&1 && { /usr/lib/xfce-polkit/xfce-polkit & }
type /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 > /dev/null 2>&1 && { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }
# type dunst > /dev/null 2>&1 && { dunst & }
type flameshot > /dev/null 2>&1 && { flameshot & }
type dropbox > /dev/null 2>&1 && { dropbox & }
type xss-lock >/dev/null 2>&1 && { xss-lock -- "$HOME/.dotfiles/bin/lock" & }
type xssproxy > /dev/null 2>&1 && { xssproxy & }
type blueman-applet > /dev/null 2>&1 && { blueman-applet & }
#type picom > /dev/null 2>&1 && { picom & }
type udiskie > /dev/null 2>&1 && { udiskie --tray --no-automount --notify & }

exec i3
