export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export QT_AUTO_SCREEN_SCALE_FACTOR=1

pulseaudio --start &
dropbox &
compton --config $HOME/.compton.conf &
urxvtd -q -f &
dunst &

#xrandr --output HDMI-A-0 --dpi 192x192
#xrandr --output DP-4 --mode 3840x2160 --dpi 168
xrdb -merge "${HOME}/.Xresources"
wal -i "$(< "${HOME}/.cache/wal/wal")"
