---
- hosts: localhost
  tasks:
    - name: Set roles
      set_fact:
        default_roles: "{{ default_roles | difference(exclude_roles | default([])) }}"

    - name: Display default roles
      debug: "var=default_roles"
    - name: Run default_roles
      include_role:
        name: "{{ item }}"
      with_items: "{{ default_roles }}"

    - name: Display extra roles
      debug: "var=extra_roles"
      when: extra_roles is defined
    - name: Run extra_roles
      include_role:
        name: "{{ item }}"
      with_items: "{{ extra_roles }}"
      when: extra_roles is defined

    - name: Display desktop roles
      debug: "var=desktop_roles"
      when: desktop_roles is defined
    - name: Run desktop_roles
      include_role:
        name: "{{ item }}"
      with_items: "{{ desktop_roles }}"
      when: desktop_roles is defined
