# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
  eval `/usr/libexec/path_helper -s`
fi

export BAT_THEME="OneHalfLight"

plugins=()

# vim shortcuts
bindkey -e

# shortcut to this dotfiles path is $DOTFILES
export DOTFILES=$HOME/.dotfiles
export ZSH=$DOTFILES/zsh

# Configure vim/nvim as editor
if type nvim > /dev/null 2>&1;then
  export EDITOR=nvim
else
  export EDITOR=vim
fi

# source every .zsh file in this rep
for config_file ($DOTFILES/zsh/*.zsh) do
  source $config_file
done

# use .localrc for SUPER SECRET CRAP that you don't
# want in your public, versioned repo.
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

export LC_CTYPE=en_US.UTF-8

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U promptinit && promptinit
autoload colors && colors
autoload -U compinit && compinit
autoload -U edit-command-line
zle -N edit-command-line
#bindkey -M vicmd v edit-command-line
bindkey '^X^E' edit-command-line

prompt smgt
