# Nightfox Wezterm Colors
# Style: dawnfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dawnfox/nightfox_wezterm.toml
[colors]
foreground = "#575279"
background = "#faf4ed"
cursor_bg = "#575279"
cursor_border = "#575279"
cursor_fg = "#faf4ed"
selection_bg = "#E1DCD5"
selection_fg = "#575279"
ansi = ["#575279", "#b4637a", "#618774", "#ea9d34", "#286983", "#907aa9", "#56949f", "#e5e9f0"]
brights = ["#5F5695", "#C26D85", "#629F81", "#EEA846", "#2D81A3", "#9A80B9", "#5CA7B4", "#E6EBF3"]
  