# Sonokai maia
[colors]
foreground = "#e1e2e3"
background = "#273136"

cursor_bg = "#575279"
cursor_border = "#575279"

cursor_fg = "#faf4ed"

selection_bg = "#E1DCD5"
selection_fg = "#575279"

ansi = ["#1c1e1f", "#f76c7c", "#9cd57b", "#e3d367", "#78cee9", "#baa0f8", "#f3a96a", "#e1e2e3"]
brights = ["#1c1e1f", "#f76c7c", "#9cd57b", "#e3d367", "#78cee9", "#baa0f8", "#f3a96a", "#e1e2e3"]
