# Sonokai default
[colors]
foreground = "#e2e2e3"
background = "#2c2e34"

cursor_bg = "#575279"
cursor_border = "#575279"

cursor_fg = "#faf4ed"

selection_bg = "#E1DCD5"
selection_fg = "#575279"

ansi = ["#181819", "#fc5d7c", "#9ed072", "#e7c664", "#76cce0", "#b39df3", "#f39660", "#e2e2e3"]
brights = ["#181819", "#fc5d7c", "#9ed072", "#e7c664", "#76cce0", "#b39df3", "#f39660", "#e2e2e3"]
