# Nightfox Wezterm Colors
# Style: dayfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/dayfox/nightfox_wezterm.toml
[colors]
foreground = "#1D344F"
background = "#EAEAEA"
cursor_bg = "#1D344F"
cursor_border = "#1D344F"
cursor_fg = "#EAEAEA"
selection_bg = "#D3D3D3"
selection_fg = "#1D344F"
ansi = ["#1d344f", "#B95D76", "#618774", "#BA793E", "#6080b0", "#8e6f98", "#6CA7BD", "#cdd1d5"]
brights = ["#24476F", "#C76882", "#629F81", "#CA884A", "#678ABF", "#9F75AC", "#74B2C9", "#CFD6DD"]
  